# Generated by Django 3.2.25 on 2025-03-30 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siesta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs', models.IntegerField(default=400, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sampling Rate')),
                ('epoch', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Epoch')),
                ('ECoG1_chan', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ECoG1 Channel')),
                ('ECoG2_chan', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ECoG2 Channel')),
                ('EMG_chan', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='EMG Channel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_training_data', models.BooleanField(default=False, verbose_name='Files for training')),
                ('cache_new_model', models.BooleanField(default=False, verbose_name='Save new model to cache?')),
            ],
        ),
    ]
