# Generated by Django 3.2.25 on 2025-03-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siesta_app', '0002_featureextraction_trainingfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureextraction',
            name='ECoG2_chan',
        ),
    ]
