# Generated by Django 3.2.25 on 2025-03-30 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siesta_app', '0003_remove_featureextraction_ecog2_chan'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureextraction',
            name='ECoG2_chan',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ECoG2 Channel'),
        ),
    ]
