# Generated by Django 3.2.25 on 2025-04-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siesta_app', '0004_featureextraction_ecog2_chan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingFiles',
        ),
    ]
